apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ongi-back.fullname" . }}-secret
  labels:
    {{- include "ongi-back.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.secrets.DB_PASSWORD | b64enc | quote }}
