apiVersion: v2
name: ongi-back
description: A Helm chart for Ongi Backend API Server
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - ongi
  - backend
  - golang
  - fiber
maintainers:
  - name: Ongi Team

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
